version: '2'

services:
  rocketchat:
    container_name: rocketchat
    image: rocketchat/rocket.chat:0.51.0
    depends_on:
      - rocketchat_db
    volumes:
      - rocketchat_uploads:/app/uploads
    networks:
      - backbone
    expose:
      - 3000
    environment:
      - "PORT=3000"
      - "ROOT_URL=http://localhost:3000"
      - "MONGO_URL=mongodb://rocketchat_db:27017/rocketchat"

  rocketchat_db:
    container_name: rocketchat_db
    image: mongo:3.2
    volumes:
      - rocketchat_mongo_data:/data/db
    command: mongod --smallfiles --oplogSize 128
    networks:
      - backbone
    expose:
      - 27017

networks:
  backbone:
    external:
      name: ${DOCKER_NETWORK_NAME}

volumes:
  rocketchat_mongo_data:
    driver: local
  rocketchat_uploads:
    driver: local
